---
abstract: 'Tools for working with Gentoo Overlays'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  FindBin: '0'
  Test::Fatal: '0'
  Test::More: '0.96'
  Test::Output: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gentoo-Overlay
no_index:
  directory:
    - corpus
    - t
provides:
  Gentoo::Overlay:
    file: lib/Gentoo/Overlay.pm
    version: '2.001002'
  Gentoo::Overlay::Category:
    file: lib/Gentoo/Overlay/Category.pm
    version: '2.001002'
  Gentoo::Overlay::Ebuild:
    file: lib/Gentoo/Overlay/Ebuild.pm
    version: '2.001002'
  Gentoo::Overlay::Exceptions:
    file: lib/Gentoo/Overlay/Exceptions.pm
    version: '2.001002'
  Gentoo::Overlay::Package:
    file: lib/Gentoo/Overlay/Package.pm
    version: '2.001002'
  Gentoo::Overlay::Types:
    file: lib/Gentoo/Overlay/Types.pm
    version: '2.001002'
requires:
  Carp: '0'
  Const::Fast: '0'
  Moo: '1.006000'
  MooX::ClassAttribute: '0'
  MooX::HandlesVia: '0'
  MooseX::Has::Sugar: '0'
  StackTrace::Auto: '0'
  String::Errf: '0'
  Sub::Exporter::Progressive: '0'
  Throwable: '0'
  Try::Tiny: '0'
  Type::Library: '0.008'
  Type::Utils: '0'
  Types::Path::Tiny: '0'
  Types::Standard: '0'
  namespace::clean: '0'
  overload: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Gentoo-Overlay/issues
  homepage: https://github.com/kentnl/Gentoo-Overlay
  repository: https://github.com/kentnl/Gentoo-Overlay.git
version: '2.001002'
